// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxorvkzpaiwmhlnttbjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4b3J2a3pwYWl3bWhsbnR0Ymp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzk5MzYsImV4cCI6MjA2MzYxNTkzNn0.NNKR04S0hibafKHh84dx9kdTqmacVSpsEHxKX-KqxAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);